### ISSUE TITLE
ERR_INVALID_URL

### ISSUE THREAD

**Issue by stephenkeep-eurostar** [zlurad/serp-parser#55]
I am getting an error when trying to get the SERP data from this query:

https://www.google.com/search?q=things+to+do+in+paris

Here is the error I am getting:

TypeError [ERR_INVALID_URL]: Invalid URL: /aclk?sa=l&ai=DChcSEwjFq8SGp7_nAhURboYKHch9B64YABABGgJ2dQ&ae=1&sig=AOD64_0JWC2vYtYgE3zABvQ2HPA8ExqmMw&adurl=https://www.airbnb.com/s/Paris/things-to-do%3Frefinement_paths%5B%5D%3D/things_to_do/%26af%3D8781787%26c%3D.pi0.pk44417100850_233371952286_c_299862761468%26gclid%3DEAIaIQobChMIxavEhqe_5wIVEW6GCh3IfQeuEAAYAiAAEgLK3_D_BwE&q=

It seems to be an error with handling the Ad URLs.

**Comment by badluck13** [comment]
Hi @stephenkeep-eurostar 

Seems they changed the way it handles `href` on the ad links, it will be fixed on the next version. 

We'll ship it in the next day or two.

**Comment by stephenkeep-eurostar** [comment]
Amazing thanks!

**Comment by badluck13** [comment]
@stephenkeep-eurostar it should work now with `serp-parser` v0.4.1

**Comment by marcelinhov2** [comment]
hey @badluck13, I think this error is back.
![image](https://user-images.githubusercontent.com/232648/152824494-767a3d32-e8be-440e-844b-205290dafe61.png)
